### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by zats**
As promised 🙂

### CODE REVIEW

**Comment by leonardvandriel** [comment]
Thanks!

**Comment by zats** [comment]
Thank you!
A quick question, do I understand correctly that this implementation uses
v1 of APNS protocol?

**Comment by leonardvandriel** [comment]
It supports three binary formats, the default being the "Binary Interface and Notification Format" defined in `kNWNotificationType2`. See `NWType.h` for more info. There's no support for the new HTTP/2 interface.

Does that answer your question?

**Comment by zats** [comment]
Yes it does, I’ll check it out, thanks!!

**Pull request merged**
