### PR TITLE
Extract OS X and iOS frameworks to allow modularity

### PR DESCRIPTION
**Pull request by zats**
Hi, I wanted to leverage your great code in one of my projects without pulling the dependancies manually.
For that I extracted relevant aspects into OS X and iOS frameworks allowing to use project through Carthage dependency manager. It doesn't affect existent projects in any way, except for bumping minimum required version for iOS app to 8.0, which is the minimum version allowing embedded frameworks.

### CODE REVIEW

**Comment by leonardvandriel** [comment]
Hi Zats, that looks good. Would you be able to add a small entry to the `README.md` about this?

**Comment by zats** [comment]
will do later today! 👍

**Comment by danat8x8** [comment]
I need this too :)  How can I build the framework?

**Comment by zats** [comment]
there are 2 new targets in the project now: OS X & iOS frameworks, you can either drop it in the project as a build dependency or use Carthage, please see the readme for details.

**Comment by danat8x8** [comment]
Carthage output:

*** Cloning NWPusher
*** Checking out NWPusher at "0.7.1"
*** xcodebuild output can be found in /var/folders/w4/x6y651ks4zq9jx00gbth2wd5hlmvrr/T/carthage-xcodebuild.cIbKZB.log
*** Skipped building NWPusher due to the error:
Dependency "NWPusher" has no shared framework schemes

and weirdly:

**Comment by zats** [comment]
Oh, good point, it seems like my tags did not get merged from my repo over to @noodlewerk 
What happens now is that latest semantically tagged version still points to the version of the repo without frameworks.
@leonardvandriel any chance you can add a `0.7.2` tag to point to the latest master
@danat8x8 in the meantime please try to point to the `master` https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement:

```
github "noodlewerk/NWPusher" "master"
```

**Comment by danat8x8** [comment]
Yes, building from master works, thanks!

**Comment by leonardvandriel** [comment]
just added 0.7.2 tag

**Comment by zats** [comment]
Thanks a lot, @leonardvandriel 🎉

**Comment by leonardvandriel** [comment]
@zats: I sneak-pushed another tag with bumped version numbers, hope that's okay. In there Xcode changed the xcscheme file. Can you check it that doesn't break your work?

**Comment by zats** [comment]
installs just fine 👍

**Pull request merged**
