### PR TITLE
Added possibility to use VoIP certificates used for PushKit.

### PR DESCRIPTION
**Pull request by 666tos**
Added possibility to use VoIP certificates used for PushKit.
Added possibility to switch server on-the-fly (necessary for VoIP pushes).

### CODE REVIEW

**Comment by leonardvandriel** [comment]
Hi, thanks for sharing your changes. I'll need some time to review these and get back to you later this week.

**Comment by 666tos** [comment]
Ok, perfect. Change is pretty big, but i hope it's useful

**Comment by Jalamanta** [comment]
Any update on this?

**Comment by whiskey** [comment]
*shameless bump*

**Pull request merged**
